### ISSUE TITLE
PHP active Record

### ISSUE THREAD

**Issue by israelsousa21** [kla/smoothie#1]
Hi, Sorry to post out contente, but Um here to avise the Domain phpactiverecord.org os not online anymore. I Saw you onde of developer of this ORM, I Hope tou can back It online again. I need the documentário. Thanx for the attention

**Comment by kla** [comment]
See my reply at https://github.com/jpfuentes2/php-activerecord/issues/573

**Comment by israelsousa21** [comment]
Thanx a Lot :)
